#ifndef _GPU_CONFIG_H_
#define _GPU_CONFIG_H_

/**
 * \file GPU/Config.h
 * 
 * This file guides compilation of the library, and facilitates any pre-processor 
 * logic that may be required by users of the library. Config.h is always at the top
 * of the include path for all GPU headers.  If you have recived GPU as a
 * pre-compiled distribution, do not edit this file.  Headers depend on
 * this file being the same as when the library was compiled.
 *
 * If you are compiling yourself, you can make changes as noted to configure
 * the compilation.  Unless otherwise specified, all GPU configuration
 * should be implemented in this file.  Command line definition of GPU preprocessor
 * configuration constants is discouraged, and can result in defective binary
 * distributions.
 *
 * The following pre-processor flags should be defined for compilation:
 *  - GPU_COMPILE: Defined when the GPU library is being compiled.
 *  - GPU_DYNAMIC_COMPILE: Defined when the GPU library is being compiled as a dynamic library.
 *    This implies definition GPU_COMPILE.
 */

/**
 * \def GPU_DYNAMIC_LIB
 * Define if being compiled or used as a dynamic library.
 */

/**
 * \def GPU_SUPPORT_DIRECT_X
 * Indicates that support for the GPU related APIs DirectX family of APIs is
 * compiled into the GPU library.  This includes Direct3D, HLSL, and DirectCompute.
 */
#define GPU_SUPPORT_DIRECT_X

/**
 * \def GPU_SUPPORT_OPEN_GL
 * Indicates that support for the OpenGL family of APIs is compiled into the GPU library.  This
 * includes OpenGL, GLSL, and OpenCL.
 */
#define GPU_SUPPORT_OPEN_GL

///////////////////////////////////////////////////////
///////////// DO NOT EDIT BELOW THIS LINE /////////////
///////////////////////////////////////////////////////

#if defined(GPU_DYNAMIC_COMPILE) && !defined(GPU_COMPILE)
#	define GPU_COMPILE
#endif

#if defined(_WIN32) && !defined(NOMINMAX)
#	define NOMINMAX
#	undef min
#	undef max
#endif

#if !defined(GPU_DYNAMIC_LIB)
#	define GPU_DYNAMIC_FUNC_EXPORT
#	define GPU_DYNAMIC_CLASS
#	define GPU_DYNAMIC_FUNC_DECLARE
#elif defined(_WIN32)
#	if defined(GPU_COMPILE)
#		define GPU_DYNAMIC_FUNC_EXPORT extern __declspec(dllexport)
#		define GPU_DYNAMIC_CLASS __declspec(dllexport)
#	else
#		define GPU_DYNAMIC_FUNC_EXPORT extern
#		define GPU_DYNAMIC_CLASS __declspec(dllimport)
#	endif
#endif

#endif // _GPU_CONFIG_H_